In [1]:
x = 12

In [2]:
[x]

[12]

In [3]:
[x] * 5

[12, 12, 12, 12, 12]

In [8]:
import numpy as np
import random

valid_size = 16 # Random set of words to evaluate similarity on.
valid_window = 100
# pick 8 samples from (0,100) and (1000,1100) each ranges. lower id implies more frequent 
valid_examples = np.array(random.sample(range(valid_window), valid_size//2))
valid_examples

array([49, 96, 28,  0, 43, 97, 15, 35])

In [12]:
valid_examples = np.append(valid_examples, 
                               random.sample(range(1000,1000+valid_window), valid_size//2))
valid_examples

array([  49,   96,   28,    0,   43,   97,   15,   35, 1011, 1034, 1027,
       1079, 1048, 1013, 1085, 1093, 1057, 1063, 1080, 1085, 1010, 1059,
       1039, 1074, 1001, 1009, 1092, 1016, 1062, 1063, 1010, 1078, 1001,
       1077, 1057, 1083, 1024, 1030, 1053, 1097])

In [13]:
import tensorflow as tf

In [21]:
embedding = tf.constant([[0.1, 0.3, -0.4],
                         [-0.2, -0.8, 0.5],
                         [0.7, 0.9, -0.6]])
a = tf.square(embedding)
b = tf.reduce_sum(a, 1, keep_dims=True)
c = tf.sqrt(b)

In [22]:
with tf.Session() as sess:
    out_a = sess.run(a)
    print(out_a)
    out_b = sess.run(b)
    print(out_b)
    out_c = sess.run(c)
    print(out_c)

[[ 0.01        0.09        0.16000001]
 [ 0.04        0.64000005  0.25      ]
 [ 0.48999998  0.80999994  0.36000001]]
[[ 0.26000002]
 [ 0.93000007]
 [ 1.65999997]]
[[ 0.509902  ]
 [ 0.96436512]
 [ 1.28840983]]
